---
- name: Set scala_bundle_name
  set_fact:
    scala_bundle_name: "scala-{{ scala_version }}"
- debug: var=scala_bundle_name

#- name: Load scala binary tarbll MD5
#  set_fact:
#    scala_binary_md5: "{{ item.split(': ')|last|replace(' ', '')|lower }}"
#  with_url: [ "{{ scala_url_base }}/{{ scala_version }}/{{ scala_bundle_name }}.tgz.md5" ]
#- debug: var=scala_binary_md5

- name: Download scala binary tarball
  get_url:
    url: "{{ scala_url_base }}/{{ scala_version }}/{{ scala_bundle_name }}.tgz"
    dest: "{{ scala_cache_dir }}/{{ scala_bundle_name }}.tgz"
#   checksum: md5:{{ scala_binary_md5 }}

- name: Ensure {{ scala_dir_base }} exists
  file: path={{ scala_dir_base }} state=directory
  become: yes

- name: Unpack Scala distribution
  unarchive:
    src:   "{{ scala_bundle_name }}.tgz"
    dest:  "{{ scala_dir_base }}"
    owner: root
    group: root
    creates: "{{ scala_dir_base }}/{{ scala_bundle_name }}/doc/LICENSE.md"
  become: yes

- name: Create canonical folder with symlink
  file: state=link path={{ scala_dir_base }}/scala src={{ scala_bundle_name }}
  become: yes

- name: Set environment variables globally
  template: src=profile.sh.j2 dest=/etc/profile.d/scala.sh
  become: true

